### ISSUE TITLE
Providing username in tag returns 302

### ISSUE THREAD

**Issue by Golemas7** [redsquirrelstudio/insta-vue#2]
If we provide the instagram profile username in the tag field we get 302 response. Used to work properly a few weeks ago.
It works fine with hashtags.

**Comment by redsquirrelstudio** [comment]
Hi there, thanks for raising an issue,
Can I ask what the account handle was?

**Comment by Golemas7** [comment]
It does not matter, I tried with redsquirrelstudio and  and it didn't work as well.

**Comment by Golemas7** [comment]
Although it was failing seems like it started working just now, did you change anything?

**Comment by redsquirrelstudio** [comment]
Nope, I haven't, The component relies on Instagram's API route so may have just had a funny five minutes. As a note, any changes I make will only be applied to your project by updating the npm dependency. Again thank you anyways :)
