### ISSUE TITLE
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Apadolsky** [redsquirrelstudio/insta-vue#3]
Providing username (tag="redsquirrelstudio" ) returns a syntax error and no photos appear. I tried multiple user names with the same error. 

Using a hashtag (tag="#programming") works. I used multiple hash tags and they all worked. 

Attached is a screen shot of the error in the console. 

Thanks!

<img width="443" alt="Screen Shot 2020-12-24 at 12 43 19 PM" src="https://user-images.githubusercontent.com/59741504/103104908-82d9b600-45e7-11eb-8c13-ad76117178a9.png">

**Comment by redsquirrelstudio** [comment]
Hi there, thank you for reporting this, I shall look into it just after Christmas:)

**Comment by redsquirrelstudio** [comment]
The issue should be sorted in the latest version

**Comment by Apadolsky** [comment]
Thanks! Appreciate the work and quick fix!

**Comment by Apadolsky** [comment]
I re-installed the new package and I am still getting the same error. Hashtags work and usernames result in the error attached. Am I missing something? Thank you.

<img width="598" alt="Screen Shot 2020-12-28 at 8 39 25 AM" src="https://user-images.githubusercontent.com/59741504/103225974-588a4000-48e8-11eb-9d0b-287daa4d2569.png">

**Comment by redsquirrelstudio** [comment]
Hi, can I ask which browser and version of Vue or Nuxt you are using? Thanks :)

**Comment by Apadolsky** [comment]
I have tried in Safari V 14.0.1 and Chrome V 87.0.4280.88

package.json
Vue Version ^2.6.12

**Comment by redsquirrelstudio** [comment]
And just to confirm, you're on V1.1.0 of insta-vue, is there a live site you have up where this error is showing?

**Comment by Apadolsky** [comment]
Correct "insta-vue": "^1.1.0". 

yes. https://paintboxwebsites.com/

Thanks

**Comment by redsquirrelstudio** [comment]
Quite strange, on Latest chrome, I'm not seeing it 
![image](https://user-images.githubusercontent.com/46108903/103230576-b55c1980-492d-11eb-9c2c-a1a01b9a57c4.png)

**Comment by Apadolsky** [comment]
Weird. My Chrome is up to date and I receive the error. 

Glad, it shows on your end.  Thanks for your help. 

<img width="1272" alt="Screen Shot 2020-12-28 at 9 59 39 AM" src="https://user-images.githubusercontent.com/59741504/103230790-8aed6a80-48f3-11eb-8b59-e363ffa31d62.png">

**Comment by redsquirrelstudio** [comment]
One thing it may be that I've found with the component, 
If you've been refreshing the site quite a bit, i've found Instagram will throttle the requests you make, this will reflect across your wifi network. Give it a few days and it'll come back :)

**Comment by Apadolsky** [comment]
Thanks for the tip, I turned off wi-fi and tried on cell data and it works great. Thanks for your time and work on this plugin.
